### ISSUE TITLE
equivalent files to hg19 extdata for GRCh38

### ISSUE THREAD

**Issue by avilella** [broadinstitute/ichorCNA#1]
Hi, I am testing ichorCNA on bam files aligned to GRCh38 (chromosomes with 'chr' notation).

I managed to create the wig file, delete the 'chr' from it, but when trying to run ichorCNA, it complains about a mismatch of elements (3053 elements in value to replace 3044). I presume this is because it uses reference files from hg19 in the `ichorCNA/extdata` folder:

gc_hg19_1000kb.wig
gc_hg19_500kb.wig
GRCh37.p13_centromere_UCSC-gapTable.txt
HD_ULP_PoN_1Mb_median_normAutosome_mapScoreFiltered_median.rds
HD_ULP_PoN_500kb_median_normAutosome_mapScoreFiltered_median.rds
map_hg19_1000kb.wig
map_hg19_500kb.wig
MBC_315.ctDNA.reads.wig
MBC_315_T2.ctDNA.reads.wig

Would it be possible to generate equivalent files for GRCh38?

**Comment by gavinha** [comment]
Hi Albert,

We have added GC and centromere reference files for hg38.  Unfortunately, we are not able to provide the mappability file at the moment.  I think it is actually not critical to use the mappability file so hopefully it'll be fine for you as well.  Also, you will not be able to use the existing HD_ULP_PoN file; this is a panel of normals sequenced from the cfDNA of healthy donors to help with some biases in low coverage sequencing data.  However, you can create your own.  We will provide a script and some instructions.

If you are using the snakemake workflow, you'll want to specify these files here:
https://github.com/broadinstitute/ichorCNA/blob/05c7f1f5849d04ffc4199a8a5cbb1f85c644c9c4/scripts/snakemake/config/config.yaml#L10-L13

If you are using the [scripts/runIchorCNA.R](https://github.com/broadinstitute/ichorCNA/blob/master/scripts/runIchorCNA.R) directly from the command line, you can specify these files using `--gcWig` and `--centromere` arguments.

Finally, the NCBI and UCSC chromosome naming convention should not be a problem.  That is, you do not need to remove "chr" from the chromosomes.  At the moment, [scripts/runIchorCNA.R](https://github.com/broadinstitute/ichorCNA/blob/master/scripts/runIchorCNA.R) will accept any format and using `GenomeInfoDb` R package functions, will properly read the chromosomes.  However, you can set the desired output format using the `genomeStyle` parameter in loadReadCountsFromWig, which is currently set to `NCBI` (e.g. 1 instead of chr1).  You can use `genomeStyle="UCSC` to use `chr1`.
https://github.com/broadinstitute/ichorCNA/blob/05c7f1f5849d04ffc4199a8a5cbb1f85c644c9c4/scripts/runIchorCNA.R#L168

**Comment by jurhoades** [comment]
Hi Albert,

I've made some updates to ichorCNA and tested to verify that it can run both with and without the "chr" contig names as well as with BAMs aligned to hg38.  You should now see equivalent reference files for hg38 (excluding mappability) that you can use with your BAM files.  I've also gone ahead and realigned our healthy donor PoN to hg38 and regenerated an `.rds` version of the PoN that can be used with the `--normalPanel` parameter.  As Gavin explained here (#3) this PoN helps to filter out systematic biases specific to the library construction and sequencing protocols we use for all of our cfDNA  samples.  It may not be specific to your samples but may help to reduce the noise in your data.

**Comment by avilella** [comment]
Thanks. I did a git pull and re-ran my example dataset:

```
[...]
runEM iter11: Expectation
runEM iter11: Maximization
Sample1 n=0.8138, sp=0.3594, phi=2.867, lambda=11.631,14.7,19.141,25.183,22.661,48.817,17.437, F=-986.8
runEM iter 11  Log likelihood: -973.477693198388
runEM iter11 Time: 0.019 min.
runEM iter10: Re-calculating responsibilties from converged parameters.
runEM: Using optimal parameters from iter10
runEM: Total elapsed time: 0.37min.
runViterbi: Segmenting and classifying
Total ULP-WGS HMM Runtime: 3.6 min.
Writing segments to .//tumor_sample.seg
Outputting to bin-level results to .//tumor_sample.cna.seg
```

It produced a `.seg` file that I browsed a bit. There are NEUT regions, as well as HETD, GAIN, AMP, and HLAMP regions:

```
cat .//tumor_sample.cna.seg | awk '{print $5}' | sort | uniq -c | sort -nrk1
   1219 NEUT
    735 HETD
    535 GAIN
    368 AMP
     66 HLAMP
      1 tumor_sample.event
```
