### ISSUE TITLE
Error in `[[<-`(`*tmp*`, name, value = c(-1, -1, 0.598332, 0.539498, 0.594508,  :

### ISSUE THREAD

**Issue by haoziyeung** [broadinstitute/ichorCNA#14]
Hello,i'm using ichorCNA in TitanCNA snakemake pipeline,my command is 
`Rscript /gpfs/users/yanghao/software/ichorCNA/scripts/runIchorCNA.R --id tumor_sample_1 --WIG results/readDepth/tumor_sample_1.bin10000.wig --gcWig /gpfs/users/yanghao/software/ichorCNA/inst/extdata/gc_hg19_500kb.wig --mapWig /gpfs/users/yanghao/software/ichorCNA/inst/extdata/map_hg19_500kb.wig --NORMWIG results/readDepth/normal_sample_1.bin10000.wig --ploidy "c(2,3)" --normal "c(0.5)" --maxCN 8 --includeHOMD False --chrs "c(1:22, \"X\")" --chrTrain "c(1:22)" --estimateNormal True --estimatePloidy True --estimateScPrevalence True --scStates "c(1,3)" --centromere /gpfs/users/yanghao/software/ichorCNA/inst/extdata/GRCh37.p13_centromere_UCSC-gapTable.txt --txnE 0.9999 --txnStrength 10000 --fracReadsInChrYForMale 0.001 --plotFileType png --plotYLim "c(-2,4)" --outDir results/ichorCNA/tumor_sample_1/`
and output log:

$WIG
[1] "results/readDepth/tumor_sample_1.bin10000.wig"

$NORMWIG
[1] "results/readDepth/normal_sample_1.bin10000.wig"

$gcWig
[1] "/gpfs/users/yanghao/software/ichorCNA/inst/extdata/gc_hg19_500kb.wig"

$mapWig
[1] "/gpfs/users/yanghao/software/ichorCNA/inst/extdata/map_hg19_500kb.wig"

$id
[1] "tumor_sample_1"

$centromere
[1] "/gpfs/users/yanghao/software/ichorCNA/inst/extdata/GRCh37.p13_centromere_UCSC-gapTable.txt"

$rmCentromereFlankLength
[1] 1e+05

$normal
[1] "c(0.5)"

$scStates
[1] "c(1,3)"

$lambda
[1] "NULL"

$lambdaScaleHyperParam
[1] 3

$ploidy
[1] "c(2,3)"

$maxCN
[1] 8

$estimateNormal
[1] TRUE

$estimateScPrevalence
[1] TRUE

$estimatePloidy
[1] TRUE

$maxFracCNASubclone
[1] 0.7

$maxFracGenomeSubclone
[1] 0.5

$minSegmentBins
[1] 50

$altFracThreshold
[1] 0.05

$chrNormalize
[1] "c(1:22)"

$chrTrain
[1] "c(1:22)"

$chrs
[1] "c(1:22, \"X\")"

$normalizeMaleX
[1] TRUE

$fracReadsInChrYForMale
[1] 0.001

$includeHOMD
[1] FALSE

$txnE
[1] 0.9999

$txnStrength
[1] 10000

$plotFileType
[1] "png"

$plotYLim
[1] "c(-2,4)"

$outDir
[1] "results/ichorCNA/tumor_sample_1/"

$help
[1] FALSE

Loading required package: IRanges
Loading required package: methods
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, cbind, colMeans, colnames,
    colSums, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, lengths, Map, mapply, match,
    mget, order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rowMeans, rownames, rowSums, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which, which.max, which.min

Loading required package: S4Vectors
Loading required package: stats4

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: geneplotter
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: lattice
Loading required package: annotate
Loading required package: AnnotationDbi
Loading required package: XML

Attaching package: ‘ichorCNA’

The following object is masked from ‘package:HMMcopy’:

    HMMsegment

Loading tumour file:tumor_sample_1
Slurping: results/readDepth/tumor_sample_1.bin10000.wig
Parsing: fixedStep chrom=1 start=1 step=10000 span=10000
Parsing: fixedStep chrom=2 start=1 step=10000 span=10000
Parsing: fixedStep chrom=3 start=1 step=10000 span=10000
Parsing: fixedStep chrom=4 start=1 step=10000 span=10000
Parsing: fixedStep chrom=5 start=1 step=10000 span=10000
Parsing: fixedStep chrom=6 start=1 step=10000 span=10000
Parsing: fixedStep chrom=7 start=1 step=10000 span=10000
Parsing: fixedStep chrom=8 start=1 step=10000 span=10000
Parsing: fixedStep chrom=9 start=1 step=10000 span=10000
Parsing: fixedStep chrom=10 start=1 step=10000 span=10000
Parsing: fixedStep chrom=11 start=1 step=10000 span=10000
Parsing: fixedStep chrom=12 start=1 step=10000 span=10000
Parsing: fixedStep chrom=13 start=1 step=10000 span=10000
Parsing: fixedStep chrom=14 start=1 step=10000 span=10000
Parsing: fixedStep chrom=15 start=1 step=10000 span=10000
Parsing: fixedStep chrom=16 start=1 step=10000 span=10000
Parsing: fixedStep chrom=17 start=1 step=10000 span=10000
Parsing: fixedStep chrom=18 start=1 step=10000 span=10000
Parsing: fixedStep chrom=19 start=1 step=10000 span=10000
Parsing: fixedStep chrom=20 start=1 step=10000 span=10000
Parsing: fixedStep chrom=21 start=1 step=10000 span=10000
Parsing: fixedStep chrom=22 start=1 step=10000 span=10000
Parsing: fixedStep chrom=X start=1 step=10000 span=10000
Parsing: fixedStep chrom=Y start=1 step=10000 span=10000
Sorting by decreasing chromosome size
Reading GC and mappability files
Slurping: /gpfs/users/yanghao/software/ichorCNA/inst/extdata/gc_hg19_500kb.wig
Parsing: fixedStep chrom=1 start=1 step=500000 span=500000
Parsing: fixedStep chrom=2 start=1 step=500000 span=500000
Parsing: fixedStep chrom=3 start=1 step=500000 span=500000
Parsing: fixedStep chrom=4 start=1 step=500000 span=500000
Parsing: fixedStep chrom=5 start=1 step=500000 span=500000
Parsing: fixedStep chrom=6 start=1 step=500000 span=500000
Parsing: fixedStep chrom=7 start=1 step=500000 span=500000
Parsing: fixedStep chrom=8 start=1 step=500000 span=500000
Parsing: fixedStep chrom=9 start=1 step=500000 span=500000
Parsing: fixedStep chrom=10 start=1 step=500000 span=500000
Parsing: fixedStep chrom=11 start=1 step=500000 span=500000
Parsing: fixedStep chrom=12 start=1 step=500000 span=500000
Parsing: fixedStep chrom=13 start=1 step=500000 span=500000
Parsing: fixedStep chrom=14 start=1 step=500000 span=500000
Parsing: fixedStep chrom=15 start=1 step=500000 span=500000
Parsing: fixedStep chrom=16 start=1 step=500000 span=500000
Parsing: fixedStep chrom=17 start=1 step=500000 span=500000
Parsing: fixedStep chrom=18 start=1 step=500000 span=500000
Parsing: fixedStep chrom=19 start=1 step=500000 span=500000
Parsing: fixedStep chrom=20 start=1 step=500000 span=500000
Parsing: fixedStep chrom=21 start=1 step=500000 span=500000
Parsing: fixedStep chrom=22 start=1 step=500000 span=500000
Parsing: fixedStep chrom=X start=1 step=500000 span=500000
Parsing: fixedStep chrom=Y start=1 step=500000 span=500000
Sorting by decreasing chromosome size
Slurping: /gpfs/users/yanghao/software/ichorCNA/inst/extdata/map_hg19_500kb.wig
Parsing: fixedStep chrom=1 start=1 step=500000 span=500000
Parsing: fixedStep chrom=2 start=1 step=500000 span=500000
Parsing: fixedStep chrom=3 start=1 step=500000 span=500000
Parsing: fixedStep chrom=4 start=1 step=500000 span=500000
Parsing: fixedStep chrom=5 start=1 step=500000 span=500000
Parsing: fixedStep chrom=6 start=1 step=500000 span=500000
Parsing: fixedStep chrom=7 start=1 step=500000 span=500000
Parsing: fixedStep chrom=8 start=1 step=500000 span=500000
Parsing: fixedStep chrom=9 start=1 step=500000 span=500000
Parsing: fixedStep chrom=10 start=1 step=500000 span=500000
Parsing: fixedStep chrom=11 start=1 step=500000 span=500000
Parsing: fixedStep chrom=12 start=1 step=500000 span=500000
Parsing: fixedStep chrom=13 start=1 step=500000 span=500000
Parsing: fixedStep chrom=14 start=1 step=500000 span=500000
Parsing: fixedStep chrom=15 start=1 step=500000 span=500000
Parsing: fixedStep chrom=16 start=1 step=500000 span=500000
Parsing: fixedStep chrom=17 start=1 step=500000 span=500000
Parsing: fixedStep chrom=18 start=1 step=500000 span=500000
Parsing: fixedStep chrom=19 start=1 step=500000 span=500000
Parsing: fixedStep chrom=20 start=1 step=500000 span=500000
Parsing: fixedStep chrom=21 start=1 step=500000 span=500000
Parsing: fixedStep chrom=22 start=1 step=500000 span=500000
Parsing: fixedStep chrom=X start=1 step=500000 span=500000
Parsing: fixedStep chrom=Y start=1 step=500000 span=500000
Sorting by decreasing chromosome size
Correcting Tumour
Loading required package: GenomeInfoDb
Error in `[[<-`(`*tmp*`, name, value = c(-1, -1, 0.598332, 0.539498, 0.594508,  :
  6087 elements in value to replace 303641 elements
Calls: loadReadCountsFromWig -> $<- -> $<- -> [[<- -> [[<-
Execution halted

Here is my input wig files:
Tumor:https://github.com/haoziyeung/supp_files/blob/master/tumor_sample_1.bin10000.wig
Normal:https://github.com/haoziyeung/supp_files/blob/master/normal_sample_1.bin10000.wig
Thanks a lot.

**Comment by gavinha** [comment]
Hi,

It appears your input files have different bin sizes.

`Slurping: results/readDepth/tumor_sample_1.bin10000.wig
Parsing: fixedStep chrom=1 start=1 step=10000 span=10000`

`Slurping: /gpfs/users/yanghao/software/ichorCNA/inst/extdata/gc_hg19_500kb.wig
Parsing: fixedStep chrom=1 start=1 step=500000 span=500000`

You need to provide the gc and map wig files that have the same bin size.

Best,
Gavin

**Comment by haoziyeung** [comment]
Many thanks

**Comment by daormar** [comment]
Hello, I would like to reopen this issue, since I'm experiencing a similar problem than the previous user. I've checked that bin sizes are equal for gc and map wig files. However, I continue getting the same error.

Here is my command:
``
Rscript runIchorCNA.R --id tumor --WIG  tumor.wig --gcWig  /home/dortiz/bio/software/ichorCNA/inst/extdata/gc_hg19_1000kb.wig --mapwig /home/dortiz/bio/software/ichorCNA/inst/extdata/map_hg19_1000kb.wig  --outDir outd
``
And here is the output log:

``
$WIG
[1] "tumor.wig"

$gcWig
[1] "/home/dortiz/bio/software/ichorCNA/inst/extdata/gc_hg19_1000kb.wig"

$mapWig
[1] "/home/dortiz/bio/software/ichorCNA/inst/extdata/map_hg19_1000kb.wig"

$id
[1] "tumor"

$minMapScore
[1] 0.9

$rmCentromereFlankLength
[1] 1e+05

$normal
[1] "0.5"

$scStates
[1] "NULL"

$lambda
[1] "NULL"

$lambdaScaleHyperParam
[1] 3

$ploidy
[1] "2"

$maxCN
[1] 7

$estimateNormal
[1] TRUE

$estimateScPrevalence
[1] TRUE

$estimatePloidy
[1] TRUE

$maxFracCNASubclone
[1] 0.7

$maxFracGenomeSubclone
[1] 0.5

$minSegmentBins
[1] 50

$altFracThreshold
[1] 0.05

$chrNormalize
[1] "c(1:22)"

$chrTrain
[1] "c(1:22)"

$chrs
[1] "c(1:22,\"X\")"

$genomeBuild
[1] "hg19"

$genomeStyle
[1] "NCBI"

$normalizeMaleX
[1] TRUE

$minTumFracToCorrect
[1] 0.1

$fracReadsInChrYForMale
[1] 0.001

$includeHOMD
[1] FALSE

$txnE
[1] 0.9999999

$txnStrength
[1] 1e+07

$plotFileType
[1] "pdf"

$plotYLim
[1] "c(-2,2)"

$outDir
[1] "outd"

$help
[1] FALSE

Loading required package: data.table
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which, which.max, which.min

Loading required package: S4Vectors

Attaching package: ‘S4Vectors’

The following objects are masked from ‘package:data.table’:

    first, second

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges

Attaching package: ‘IRanges’

The following object is masked from ‘package:data.table’:

    shift

Loading required package: GenomeInfoDb

Attaching package: ‘ichorCNA’

The following object is masked from ‘package:HMMcopy’:

    HMMsegment


Attaching package: ‘Biostrings’

The following object is masked from ‘package:base’:

    strsplit

Loading tumour file:tumor
Slurping: /home/dortiz/bio/tasks/idibaps/pipelines/basic/gen_tum_rcount/tumor.wig
Parsing: fixedStep chrom=1 start=1 step=1000 span=1000
Parsing: fixedStep chrom=2 start=1 step=1000 span=1000
Parsing: fixedStep chrom=3 start=1 step=1000 span=1000
Parsing: fixedStep chrom=4 start=1 step=1000 span=1000
Parsing: fixedStep chrom=5 start=1 step=1000 span=1000
Parsing: fixedStep chrom=6 start=1 step=1000 span=1000
Parsing: fixedStep chrom=7 start=1 step=1000 span=1000
Parsing: fixedStep chrom=8 start=1 step=1000 span=1000
Parsing: fixedStep chrom=9 start=1 step=1000 span=1000
Parsing: fixedStep chrom=10 start=1 step=1000 span=1000
Parsing: fixedStep chrom=11 start=1 step=1000 span=1000
Parsing: fixedStep chrom=12 start=1 step=1000 span=1000
Parsing: fixedStep chrom=13 start=1 step=1000 span=1000
Parsing: fixedStep chrom=14 start=1 step=1000 span=1000
Parsing: fixedStep chrom=15 start=1 step=1000 span=1000
Parsing: fixedStep chrom=16 start=1 step=1000 span=1000
Parsing: fixedStep chrom=17 start=1 step=1000 span=1000
Parsing: fixedStep chrom=18 start=1 step=1000 span=1000
Parsing: fixedStep chrom=19 start=1 step=1000 span=1000
Parsing: fixedStep chrom=20 start=1 step=1000 span=1000
Parsing: fixedStep chrom=21 start=1 step=1000 span=1000
Parsing: fixedStep chrom=22 start=1 step=1000 span=1000
Parsing: fixedStep chrom=X start=1 step=1000 span=1000
Parsing: fixedStep chrom=Y start=1 step=1000 span=1000
Sorting by decreasing chromosome size
Reading GC and mappability files
Slurping: /home/dortiz/bio/software/ichorCNA/inst/extdata/gc_hg19_1000kb.wig
Parsing: fixedStep chrom=1 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=2 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=3 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=4 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=5 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=6 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=7 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=8 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=9 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=10 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=11 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=12 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=13 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=14 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=15 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=16 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=17 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=18 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=19 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=20 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=21 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=22 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=X start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=Y start=1 step=1000000 span=1000000
Sorting by decreasing chromosome size
Slurping: /home/dortiz/bio/software/ichorCNA/inst/extdata/map_hg19_1000kb.wig
Parsing: fixedStep chrom=1 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=2 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=3 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=4 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=5 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=6 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=7 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=8 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=9 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=10 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=11 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=12 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=13 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=14 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=15 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=16 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=17 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=18 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=19 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=20 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=21 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=22 start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=X start=1 step=1000000 span=1000000
Parsing: fixedStep chrom=Y start=1 step=1000000 span=1000000
Sorting by decreasing chromosome size
Correcting Tumour
Error in `[[<-`(`*tmp*`, name, value = c(-1, 0.568915, -1, -1, 0.482201,  : 
  3053 elements in value to replace 3036315 elements
Calls: loadReadCountsFromWig -> $<- -> $<- -> [[<- -> [[<-
Execution halted
``

Please tell me if any additional information is required.
Thanks in Advance

**Comment by gavinha** [comment]
Hi @daormar 

Please check your wig files again.  Your `tumor.wig` has 1kb bins and the GC/map wig files have 1000kb bins.

```
Loading tumour file:tumor
Slurping: /home/dortiz/bio/tasks/idibaps/pipelines/basic/gen_tum_rcount/tumor.wig
Parsing: fixedStep chrom=1 start=1 step=1000 span=1000
```

```
Reading GC and mappability files
Slurping: /home/dortiz/bio/software/ichorCNA/inst/extdata/gc_hg19_1000kb.wig
Parsing: fixedStep chrom=1 start=1 step=1000000 span=1000000
```

Best,
Gavin

**Comment by pawelqs** [comment]
I got the same problem, but use the same bin sizes. I have WGS data and do not provide exons file. May it be the reason?

> Loading required package: data.table
> Loading required package: stats4
> Loading required package: BiocGenerics
> Loading required package: parallel
> 
> Attaching package: ‘BiocGenerics’
> 
> The following objects are masked from ‘package:parallel’:
> 
>     clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
>     clusterExport, clusterMap, parApply, parCapply, parLapply,
>     parLapplyLB, parRapply, parSapply, parSapplyLB
> 
> The following objects are masked from ‘package:stats’:
> 
>     IQR, mad, sd, var, xtabs
> 
> The following objects are masked from ‘package:base’:
> 
>     anyDuplicated, append, as.data.frame, basename, cbind, colnames,
>     dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
>     grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
>     order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
>     rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
>     union, unique, unsplit, which, which.max, which.min
> 
> Loading required package: S4Vectors
> 
> Attaching package: ‘S4Vectors’
> 
> The following objects are masked from ‘package:data.table’:
> 
>     first, second
> 
> The following object is masked from ‘package:base’:
> 
>     expand.grid
> 
> Loading required package: IRanges
> 
> Attaching package: ‘IRanges’
> 
> The following object is masked from ‘package:data.table’:
> 
>     shift
> 
> Loading required package: GenomeInfoDb
> 
> Attaching package: ‘Biostrings’
> 
> The following object is masked from ‘package:base’:
> 
>     strsplit
> 
> Loading tumour file:AMLRO-8_Rx
> Slurping: results/readDepth/AMLRO-8_Rx.bin10000.wig
> Parsing: fixedStep chrom=chr1 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr2 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr3 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr4 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr5 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr6 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr7 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr8 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr9 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr10 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr11 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr12 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr13 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr14 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr15 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr16 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr17 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr18 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr19 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr20 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr21 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr22 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chrX start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chrY start=1 step=10000 span=10000
> Sorting by decreasing chromosome size
> Reading GC and mappability files
> Slurping: /home/pkus/opus_wes/workflow/scripts/ichorCNA-master/inst/extdata/gc_hg38_10kb.wig
> Parsing: fixedStep chrom=chr1 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr2 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr3 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr4 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr5 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr6 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr7 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr8 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr9 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr10 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr11 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr12 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr13 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr14 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr15 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr16 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr17 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr18 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr19 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr20 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr21 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr22 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chrX start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chrY start=1 step=10000 span=10000
> Sorting by decreasing chromosome size
> Slurping: /home/pkus/opus_wes/workflow/scripts/ichorCNA-master/inst/extdata/map_hg38_10kb.wig
> Parsing: fixedStep chrom=chr1 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr2 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr3 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr4 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr5 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr6 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr7 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr8 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr9 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr10 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr11 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr12 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr13 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr14 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr15 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr16 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr17 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr18 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr19 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr20 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr21 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chr22 start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chrX start=1 step=10000 span=10000
> Parsing: fixedStep chrom=chrY start=1 step=10000 span=10000
> Sorting by decreasing chromosome size
> Correcting Tumour
> Error in `[[<-`(`*tmp*`, name, value = c(-1, 0.5923, 0.5174, 0.4712, 0.3561,  : 
>   303114 elements in value to replace 303641 elements
> Calls: loadReadCountsFromWig -> $<- -> $<- -> [[<- -> [[<-
> Execution halted

Thank you,
Paweł

**Comment by pawelqs** [comment]
Nevermind, I did not change the genome build...

**Comment by sjm5701** [comment]
> Nevermind, I did not change the genome build...
Hi, there! I am having the same problem. Could you tell me how you solved it. I changed genomeBuild hg19 to hg38 in config.yaml and runIchorCNA.R but still facing the same error.

**Comment by pawelqs** [comment]
Hi @sjm5701, 
does other fields in your config.yaml, eg. `ichorCNA_gcWig` and `ichorCNA_mapWig`, point to the right genome files?

**Comment by sjm5701** [comment]
> Hi @sjm5701,
> does other fields in your config.yaml, eg. `ichorCNA_gcWig` and `ichorCNA_mapWig`, point to the right genome files?

Yes, it is certainly pointing the right genome files. ichorCNA_gcWig to be gc_hg38_10kb.wig and ichorCNA_mapWig to be map_hg38_10kb.wig.

**Comment by pawelqs** [comment]
Hmm, hard to say... Could you paste the program output?

**Comment by sjm5701** [comment]
I ran snakemake -s ichorCNA.snakefile --core 5 and the error shown in linux was like 
[error.txt](https://github.com/broadinstitute/ichorCNA/files/6277486/error.txt)


And when I checked log it, I got the same error like you had. 
[tumor_sample_1.log](https://github.com/broadinstitute/ichorCNA/files/6277499/tumor_sample_1.log)


I haven't received my own data yet so I used public normal bam file as both normal and tumor to test whether tool is working in my laptop. (Of course, the results will show no cnv in the end of process but I just wanted to set the work environment early.) Do you think this caused the error?

**Comment by pawelqs** [comment]
I do not know if this might have caused such an error. But are you sure that your BAMs are aligned against hg38, not hg19?

**Comment by sjm5701** [comment]
> I do not know if this might have caused such an error. But are you sure that your BAMs are aligned against hg38, not hg19?

Oh, I just checked it and I found my BAM were aligned against hg 19. I should have checked this first. Thanks for your help!!!
